# sg-bukkit as microserivce behind the reverse proxy
version: '3.6'
services:
    sg-bukkit:
        build: "."
        expose:
            - "80"
        restart: always
        hostname: sg-bukkit-host
        networks:
            - dmz_net
            - default
networks:
    dmz_net: 
        external: true
